[project]
name = "114514"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sphinx>=8.3.0",
    "sphinx-intl>=2.3.1",
    "sphinx-markdown-builder>=0.6.8",
]
