name: Build Godot Chinese Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install sphinx sphinx-markdown-builder sphinx-intl
        
    - name: Clone godot-docs and godot-docs-l10n
      run: |
        git clone -b 4.x https://github.com/godotengine/godot-docs.git
        git clone -b 4.x https://github.com/godotengine/godot-docs-l10n.git
        
    - name: Create necessary directories
      run: |
        mkdir -p godot-docs/po/zh_CN
        
    - name: Sync Chinese translations
      run: |
        if [ -d "godot-docs-l10n/po/zh_CN" ]; then
          rsync -a godot-docs-l10n/po/zh_CN/ godot-docs/po/zh_CN/
        else
          echo "Warning: zh_CN directory not found in godot-docs-l10n"
          exit 1
        fi
        
    - name: Build Markdown docs
      run: |
        cd godot-docs
        sphinx-build -b markdown -D language=zh_CN . _build/markdown
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: godot-docs-zh_CN-markdown
        path: godot-docs/_build/markdown
        retention-days: 90