name: Convert Godot XML to Markdown

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ master ]  # 主分支推送时触发
    paths:
      - 'godot/doc/classes/**'  # 只有XML文件变化时才触发
      - 'main.py'  # 或者您的脚本路径
      - '.github/workflows/build.yaml'  # 或者您的工作流文件路径

jobs:
  convert-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get submodules
      run: |
        git submodule init
        git submodule update

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # 使用您需要的Python版本

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv

    - name: Run conversion script
      run: |
        source .venv/bin/activate
        uv run main.py

    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: godot-docs-markdown
        path: translated_docs/
        retention-days: 90  # 保留90天